[workspace]
members = [
    "madsim",
    "madsim-macros",
    "madsim-tokio",
    "madsim-tokio-postgres",
    "madsim-tonic",
    "madsim-tonic-build",
    "madsim-norandom",
    "tonic-example",
]
